export const BASE_CURRENCY = "BTC";
export const QUOTE_CURRENCY = "USDT";
export const PERCENT = "%";

export const PLACE_ORDER_FORM_PROFIT_DEC_PLACES = 4;

export const TAKE_PROFIT_INITIAL_FIRST_AMOUNT = 100;
export const TAKE_PROFIT_INITIAL_FIRST_PROFIT = 2;
export const TAKE_PROFIT_NEW_AMOUNT_VALUE = 20;
export const TAKE_PROFIT_UNREMOVABLE_ITEMS_COUNT = 1;

export const TAKE_PROFIT_MINIMUM_PROFIT_VALUE = 0.01;
export const TAKE_PROFIT_MINIMUM_PRICE_VALUE = 0;
export const TAKE_PROFIT_MAX_PROFIT_SUMM = 500;
export const TAKE_PROFIT_MAX_AMOUNT_SUMM = 100;
export const TAKE_PROFIT_PRICE_DEC_PLACES = 2;
export const TAKE_PROFIT_PROFIT_DEC_PLACES = 3;